# Site settings
title: Aamir Nasir
email: TheAamirNasir@gmail.com
url: https://github.com/TheAamirNasir
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Data Scientist"
meta_author: Nasir Aamir

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 222222 #80B3FF
  primary-rgb: "34,34,34" #"128,179,255"
  secondary: 111111 #FD6E8A
  secondary-dark: 222222 #A2122F

# Footer settings
footer:
  copyright: Aamir Nasir
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/TheAamirNasir
  - title: facebook
    url: https://www.facebook.com/TheAamirNasir
  - title: twitter
    url: http://twitter.com/TheAamirNasir
  - title: github
    url: http://github.com/TheAamirNasir

# Postal address (add as many lines as necessary)
address:
  #- line: 3481 Melrose Place
  - line: Silvassa, IN 396230

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
